CREATE SCHEMA app
    AUTHORIZATION postgres;

CREATE TABLE app.users(
id UUID,
full_name CHARACTER VARYING,
login CHARACTER VARYING NOT NULL,
password CHARACTER VARYING NOT NULL,
date_of_birth DATE NOT NULL,
updated_at TIMESTAMP NOT NULL,
created_at TIMESTAMP NOT NULL,
role CHARACTER VARYING NOT NULL,
CONSTRAINT users_pk PRIMARY KEY (id),
CONSTRAINT users_login_unq UNIQUE(login)
);





